/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@any-design/anyui')['Button']
    ACard: typeof import('@any-design/anyui')['Card']
    AChat: typeof import('@any-design/anyui')['Chat']
    AFloat: typeof import('@any-design/anyui')['Float']
    AForm: typeof import('@any-design/anyui')['Form']
    AFormItem: typeof import('@any-design/anyui')['FormItem']
    AInput: typeof import('@any-design/anyui')['Input']
    ASpinner: typeof import('@any-design/anyui')['Spinner']
    ATextarea: typeof import('@any-design/anyui')['Textarea']
    Chat: typeof import('./src/components/Chat.vue')['default']
    InteractiveSettings: typeof import('./src/components/InteractiveSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
